stages:
  - build
  - release

variables:
  GPG_PRIVATE_KEY: $GPG_PRIVATE_KEY
  PASSPHRASE: $PASSPHRASE
  GITLAB_TOKEN: $GITLAB_TOKEN
  GO_VERSION: "1.22.8"

default:
  tags:
    - "terraform"

before_script:
  # Install the Go version specified in go.mod
  - "go version"
  - "go mod tidy"
  - "goreleaser --version"

build_job:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - "echo 'Building the application...'"
    - "go build -o terraform-provider-zstack ."
  artifacts:
    paths:
      - dist

release_job:
  stage: release
  #image: golang:${GO_VERSION}  # 使用显式指定的 Go 版本
  before_script:
    # Checkout the repository with all tags
    - "git fetch --unshallow || true"
    - "git fetch --tags"
    # Install GoReleaser
   # - "curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh"
    # Import GPG key
    - "echo \"$GPG_PRIVATE_KEY\" | gpg --import --batch --yes"
    - "echo \"passphrase: $PASSPHRASE\""
  script:
    # Run GoReleaser
    - "./bin/goreleaser release --clean"
  only:
    - main
  artifacts:
    paths:
      - dist/
