stages:
  - build

variables:
  GPG_PRIVATE_KEY: $GPG_PRIVATE_KEY
  PASSPHRASE: $PASSPHRASE
  GITLAB_TOKEN: $GITLAB_TOKEN
  GO_VERSION: "1.22.8"

default:
  tags:
    - "terraform"

before_script:
  # Install the Go version specified in go.mod
  - "go version"
  - "go mod tidy"
  - "goreleaser --version"

build_job:
  stage: build
  #image: golang:${GO_VERSION}
  script:
    - "echo 'Building the application...'"
    - "mkdir -p dist"
    - "go build -o dist/terraform-provider-zstack"
     - "tar -czf dist/terraform-provider-zstack.tar.gz dist/terraform-provider-zstack" 
  artifacts:
    paths:
      - dist/terraform-provider-zstack.tar.gz

