# .goreleaser.yml

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    # Clean up Go modules and generate code if necessary
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    # Generate zip files for each combination of OS and Arch
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    
milestones:
  - close: true

release:
  # Add extra files to the release, including the terraform-registry-manifest.json
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # You can specify release IDs here if required
  ids:
    - none
  # Optional: you may want to upload assets to GitHub Releases
  github:
    release: true  # Automatically create a release on GitHub and upload assets

signs:
  - artifacts: checksum
    args:
      - --batch
      - --detach-sign

changelog:
  # skip: true   # Uncomment to disable changelog generation if you don't need it
