name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Fetch the full Git history (required for GoReleaser to properly handle versions)
      - name: Fetch Git History
        run: git fetch --prune --unshallow

      # Step 3: Set up the Go environment (GoReleaser needs Go to build)
      - name: Set up Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"

      # Step 4: Import GPG Key (for signing releases)
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      # Step 5: Run GoReleaser to build and release the project
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
